
enum APIFunction : String
{
    case userDetail =               "user/detail"
    case userConsultant =           "user/consultant"
    case userLogin =                "user/login"
    case userLoginFacebook =        "user/login/facebook"
    case userRegister =             "user/register"
    case userUpdateAA =             "user/update/aa"
    case userUpdateToken =          "user/update/token"
    case userUpdateAvatar =         "user/update/avatar"
    case userUpdateInfo =           "user/update/info"
    case userNear =                 "user/near"
    case userSearch =               "user/search"
    case userInfo =                 "user/info"
    case uploadMedia = "upload/media"
    case referenceGroupDetail     = "book/ref/detail"
    case referenceUser     = "book/ref/user"
    case referenceDelete     = "book/ref/delete"
    case notificationSubscribe = "notification/subscribe"
    case notificationList = "notification/list"
    case notificationDelete = "notification/delete"
    case contactList = "contact/list"
    case contactAccept = "contact/accpet"
    case contactDelete = "contact/delete"
    case applicationInfo = "application/get/info"
    case deviceUpdate = "device/update"
    case newsList = "news/list"
    case newsInsert = "news/insert"
    case newsImage = "news/image"
    case newsDelete = "news/delete"
    case newsDetail = "news/detail"
    case universityList = "university/list"
    case orderInsert = "order/insert"
    case orderList = "order/list"
    case orderDetail = "order/detail"
    case orderChange = "order/change"
    case addressNode      =    "address/node"
    case fileList       =    "file/list"
    case fileInsert     =    "file/insert"
    case fileDelete     =    "file/delete"

}



